### ISSUE TITLE
Running on a pi4B shows a bar across top of screen in render and capture is worse!

### ISSUE THREAD

**Issue by danriches** [6by9/yavta#3]
Hi,

I've compiled this on a raspberry pi 4B and I get a bar across the top of the screen about 15 lines high or so. Captured images are even worse.
Captured image: https://github.com/danriches/testimages/blob/master/UNI60316d9a-19f9-496a-aa9a-1c37c81e64dd-2.jpg
Screen render: https://github.com/danriches/testimages/blob/master/pi4b_1920x1080P50_render.png

Is this something to do with an isp setting such as stride or the encoders themselves? I've checked that the output from the Roku stick (my test source) is ok with 2 different monitors and it's perfectly fine. Running on a pi3B+ shows no artifacts but doesn't run for more than around an hour whereas on the pi 4 it runs for days and days without any problems except the one I've just mentioned.

Any help you can provide would be ever so greatly appreciated.

Kind Regards,

Dan

**Comment by 6by9** [comment]
Firmware version?
Kernel version?
Comparing exactly the same firmware/kernel and app between Pi3 and Pi4?
What memory variant of Pi4? (Shouldn't make a difference).
What resolution in? (1080p50? In which case you can't be running the standard yavta against 5.4 as it'll complain about the buffers being too small - I need to add a patch to fix that)
Are you encoding to H264?
How are you capturing, to what format, and how are you viewing those images?

OK I'm on a CM4, but I'm running fine receiving 1080p50 UYVY and rendering onto a 1920x1200 HDMI monitor.

Looking at your capture it looks like you've set the source to not have any vertical padding on the format, and then fed it into something that is expecting an alignment of 16 lines (1080/16 = 67.5)

**Comment by danriches** [comment]
Hi,

I've not touched the firmware, just used the current latest image on the raspberrypi.org site which is dated 27/05/2020.

Issuing the command: vcgencmd bootloader_version
Gives:
Apr 16 2020 18:11:26
version a5e1b95f320810c69441557c5f5f0a7f2460dfb8 (release)
timestamp 1587057086

uname - a reports: Linux raspberrypi 5.4.51-v7l+ #1327 SMP Thu Jul 23 11:04:39 BST 2020 armv7l GNU/Linux

I'm using the dtoverlay drivers not the gpu unsupported ones
I've tried a 4Gb and 8Gb pi 4B and a 1Gb pi3B+ with exactly the same results on the pi 4's but not the 3.
Resolution in is 1920x1080 P50 UYVY from a TC358743 and encoding to H264.

You mention an issue with kernel 5.4 and the alignment, how can I fix that?

Thanks for your help, I've been pulling y hair out and I'm almost entirely bald (slight overstatement ;) )

Dan

**Comment by 6by9** [comment]
I've just pushed the patch to remove the padding requirement on the input of the ISP. Without that I got no preview as the ISP was rejecting the buffers.

```./yavta -T -m -c5000 -fUYVY /dev/video0 -E /dev/null``` is working fine for me image-wise with a 1080p50 source (Big Buck Bunny playing from another Pi), although I am getting some frame drops reported (the codec is only rated for 1080p30, so we are overspec).

**Comment by danriches** [comment]
Hi,

I've tried that and it's still the same. I've added in an image encoder component and every other frame from the isp is sent to the video encoder and image encoder, so it's interleaved as one frame to the video encoder and the next to the image encoder and so on.

Raised the gpu memory to 256m, no change.
Changed buffers to 8 from 3 and no real difference.
Changed JPEG quality to 70, 75, 80 and 100. 75 is the best on the pi 3B, anything else causes video encoder issues with the save_thread.

I then decided to change the line (a couple of lines above the one you just patched) from: 
`port->format->es->video.crop.height = fmt.fmt.pix.height;`
to: `port->format->es->video.crop.height = fmt.fmt.pix.height-10;`
and the screen render looks fine but both video and image encoders are still bad.
I only write a frame to the ramdisk on a gpio trigger and I've checked that the gpio code isn't interfering and it's not.

As the render is ok after setting the crop height, how would I change the video and image encoders to use the reduced height to see if that helps? As the intended source input does contain quite a bit of black space I can actually live with that.

I originally thought the issue I had was fixed but it turns out the Roku box I was using decided that it would ignore the EDID and just give out 1280x720P50 so I'm starting to wonder if it's actually possible to have a stable system streaming out 1080P50 and capturing a JPEG once in a while. Is there some way I can get the isp to drop every other frame so P50 essentially looks like P25 or P30??

I also tried the following scheme:
frame 1 & 3 -> video encoder
frame 2 -> image encoder
frame 4 -> drop deliberately
reset frame counter to 0

The h264 stream is now perfect but the image encoder is still giving me shifted output and drops the last 15 lines as junk data. Is there another image codec I can use that isn't so taxing on the gpu?

Kind Regards,

Dan

**Comment by 6by9** [comment]
If you're not using this app as-is, then this isn't the place to be repoorting issues, or at least you need to have been very explicit that you are doing so.

format->es->video.crop.height defines the active part of the buffer.
format->es->video.height defines the padded height.

All frames in from the TC358743, and those returned from the ISP come through the yavta app.

The former via [V4L2's DQBUF](https://github.com/6by9/yavta/blob/master/yavta.c#L2463), and are then passed to MMAL and the ISP via the MMAL's [mmal_port_buffer_send](https://github.com/6by9/yavta/blob/master/yavta.c#L2538) call. If you want to drop frames, then drop them there (but make sure you call ```video_queue_buffer``` with the V4L2 buffer to return it to V4L2).

The latter via [isp_output_callback](https://github.com/6by9/yavta/blob/master/yavta.c#L1804). If you want to only send one in N buffers to the encoder, then drop them there (I believe you already have some form of keying to the encoder there).

The image_encode component does require the image format to be padded, but you're using the ISP to convert from the V4L2 into whatever you want, so set the format appropriately.
After the [mmal_format_copy](https://github.com/6by9/yavta/blob/master/yavta.c#L2035), set
```
port->format->es->video.height = (port->format->es->video.crop.height + 15) & ~15;
```
(Hmm, I see the loop to drop the output resolution below 1080p actually doesn't alter width & height, only crop.width & crop.height, leaving the buffer huge with only a smaller active area. Ho hum).

**Comment by danriches** [comment]
Cheers Mr S, I'll give that a go on Monday but first time for a break. I'll let you know how it goes and as always thank you ever so much. 

Kind Regards, 

Dan

**Comment by danriches** [comment]
Hiya,

I added in the padding but left the rest of my changes as they are and it's working, at least for now so I'll keep the test running and I'm fairly sure it'll just keep working.

As always, thanks for your help, it's greatly appreciated!!

Dan

**Comment by danriches** [comment]
Hiya,

It ran for around 6 hours before falling over with a select timeout. I tried changing the code to reduce the framerate into the isp but it won't even run properly (time outs in the the save_thread). In yavta line 2463 I'm guessing this is the dequeue call you mentioned and that to reduce the framerate into the isp by not adding them to the mmal_send_buffer call at line 2538. I should also make sure I still call the function video_queue_buffer at line 2560.

Am I right in this? The reason I ask is that I've tried that and I just keep getting select timeout errors for every run regardless of whether I use the parameter -E /dev/null or -E - and pipe it to the RTSP server which reads from stdin. Do you have any ideas or comments that I can try please?

Kind Regards,

Dan

**Comment by 6by9** [comment]
select timeout just means that it's waited on V4L2 for longer than the programmed timeout. Whether that is due to the source stopping, or because you haven't returned buffers to V4L2 to fill, is something I can't say as it doesn't happen with the app as checked in to this repository.
